### ISSUE TITLE
create_taxonomic_update_lookup: Incomplete testing of `one_to_many` option

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#105]
Hi, Looking at tests, it seems there's nothing testing the behaviour of `create_taxonomic_update_lookup` when one_to_many = "most_likely_species"`

**Comment by wcornwell** [comment]
For this option, we also discussed:

1) a column that has "other_possible_matches" 
2) a warning message

**Comment by ehwenk** [comment]
I think a good idea would be to add this test to the collection of tests run on the 225 test species I created. I was already thinking that it needed to be expanded to ensure suggested_name was accurate. There could be additional tests on these same names

**Comment by ehwenk** [comment]
Closed with commit ac799c3
