### ISSUE TITLE
Review purpose of `get_updated_species_list`

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#107]
I'm not sure why this function exists in current form. It does two things, which is to run update_taxonoy and then process the outputs of this. This is confusing. I suggest either

- move `update_taxonomy` step out into parent (`create_taxonomic_update_lookup`) and rename `get_updated_species_list` to something more suitable OR
- integrate this functions behaviours into `update_taxonomy`

**Comment by wcornwell** [comment]
agreed.  

- option 1 is easy (i can do it).  

- option 2 is probably better but i'd need help. (That was the original idea but I realized I don't understand `update_taxonomy` well enough to do this well).

**Comment by dfalster** [comment]
hold off for now, until I finish working with #110
