### ISSUE TITLE
Make output messages optional

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#108]
What's the best way to silence output messages? This should be an option

**Comment by fontikar** [comment]
Output messages from align_taxa and progress bar with load_taxonomic_resources and ability to turn on and off

- How: Relevant for load_taxonomic_resources, currently prints done. Relevant for align_taxa, # of matched, checked and without match and yet to be checked is not really updating, or is it doing this super quickly? Or is it better to spit out a message after alignment as a summary or what has been aligned and what hasn't
- Acceptance criteria/ What is considered "done" here: Useful summary messages that can be flexibly switched off.

**Comment by wcornwell** [comment]
this is more or less what we discussed?
