### ISSUE TITLE
Add option to "turn off" fuzzy matching in align_taxa?

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/APCalign#12]
Hello!

Would it be possible to add an argument in `align_taxa` to set fuzzy matching to `FALSE`?

Perhaps it is an unusual use case but I'm trying to run apcnames on a list of species that includes both Australian and a large number of international taxa. I'm only interested in the Australian taxa, but as the APC is the best source of info on what taxa are found in Australia I thought apcnames might be a good way to separate Aus from international taxa. Unfortunately though the fuzzy matching in `align_taxa` coerced a large number of genuses/species not found in Aus into adjacent Australian taxa.

I've figured out a workaround but thought perhaps it could be useful to have an argument to turn fuzzy matching in `align_taxa` on or off? Or could this be dealt with by changing the `max_distance` settings?

**Comment by dfalster** [comment]
Interesting idea @rubysaltbush . We can certainly do that. Should just require a boolean (true false) argument to the function, and an if statement before starting the fuzzy matching ([e.g. here](https://github.com/traitecoevo/apcnames/blob/d472951cf82308a520a64e3766e2867e586aa753/R/clean_names.R#L157)). 

Would you like to give it a go? Clone, make the change and send a PR?

You could achieve this by setting `max_distance` = 0. The results will be the same, but doing it via the distance method will be slower, as it still calculates the distances, which is slow!

**Comment by wcornwell** [comment]
I was also looking for this.

**Comment by dfalster** [comment]
Reopening this! When merging in #41, with new matching algorithm from @ehwenk, we've lost the ability to turn fuzzy matching off. It's possible it could be reintroduced. 

My question for @ehwenk -- is it valid to use your workflow without fuzzy matching enabled?

**Comment by wcornwell** [comment]
I was thinking more about the workflow for the annuals project, which uses a dataset of about 24,000 species.  That's not really possible to run through `align_taxonomy` at the moment.  

We could just run it through `update_taxonomy` but we might be at risk of losing (all?) phrase names since GBIF formats them differently than APC.  Is there a way to isolate the fixing of formatting of phrase names from the fuzzy matching or are they too intertwined?

**Comment by dfalster** [comment]
Good use case!  How slow is it? 

Recall, Lizzy has been using this code on some very large datasets! 

I can look again at the fuzzy matching options, whether we can turn it off for first pass then back on.

For phrase names fuzzy matching is really important, as they are most likely to differ in some small way

**Comment by ehwenk** [comment]
I've run my code on 1000's of names at a time. I would start by subsetting the names to those from GBIF that aren't in APC, and running with that list. It should be much shorter.

I think if you turn off fuzzy matching you'll have lots of names that "land" at the matches at the bottom of the code that declares only a genus-level match can be made. So if you turn off fuzzy matching, you'll also want to turn off the final 2 matching steps. I suspect that without fuzzy matching, there may be some typos that suddenly become aligned to APNI names - not sure.

**Comment by wcornwell** [comment]
25723 species for the annuals project takes 55 minutes, so it's not prohibitive...

**Comment by dfalster** [comment]
Entirely reasonable, for such a large number. We could tweak it so it works in batches, that would also enable parallel processing. With 8 cores, 55 mins becomes 7 mins.

**Comment by ehwenk** [comment]
Looking back at this conversation, yes, it would be possible to turn off fuzzy matching. We'd just have to first have the T/F in the documentation and then for the fuzzy matching pieces of the taxon match, turn those off as well. And it would be good to do that. I'm wondering how best to streamline it.

**Comment by ehwenk** [comment]
closed by https://github.com/traitecoevo/APCalign/commit/e046cd2c2b170b3e275e98e2bd44ed020517da9e
