### ISSUE TITLE
`taxonomic_reference` in output of align_taxa still NA

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#124]
- How: Determine expected behaviour of taxonomic_reference in align_taxa, should this carry up to create_taxonomic_update_lookup? 
- Acceptance criteria/ What is considered "done" here: taxonomic_reference  is correct and consistent across all outputs. 

```
aligned_taxa <- align_taxa(c("Poa annua", "Abies alba", "Banksia sp."), resources = resources) 
aligned_taxa

updated_taxa <- aligned_taxa |> pull(aligned_name) |> 
  update_taxonomy(resources =resources)
updated_taxa

taxonomic_update_lookup <- create_taxonomic_update_lookup(c("Poa annua", "Abies alba", "Banksia sp."), resources = resources, full = TRUE)
taxonomic_update_lookup
```

**Comment by fontikar** [comment]
Maybe `taxonomic_ref` should just be removed from `align_taxa` ? since taxonomic_reference is for the `suggested_name`?

**Comment by ehwenk** [comment]
taxonomic_reference is a key part of how the various aligned names are manipulated in `update_taxonomy` - and hence what is carried through to the `suggested_name`. On the branch I've been working on, it should never be NA. Currently, on the main branch, it is filled in for all names in the `aligned_data` output from `align_names`. However, some of this was previously lost during either `update_taxonomy` or `create_taxonomic_update_lookup`. That is now fixed.

**Comment by fontikar** [comment]
Will revisit this when your fixes are merged  :)

**Comment by ehwenk** [comment]
@fontikar can you confirm this now works are you expect it should? I've run your example and `abies alba` of course is still NA, because not an APC/APNI name, but the others have values.

**Comment by fontikar** [comment]
Yes! its working now! 
![Screenshot 2023-08-22 at 2 36 17 pm](https://github.com/traitecoevo/APCalign/assets/12161802/2551e3d1-995b-420a-aea4-29f00bdc1518)

**Comment by ehwenk** [comment]
closed by https://github.com/traitecoevo/APCalign/commit/e0d342e0b20238f62ea34a18d5fe177ba33a0e59
