### ISSUE TITLE
error when zero species in a call match

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#129]
<img width="570" alt="Screenshot 2023-08-22 at 2 26 05 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/be78f0b9-9945-421a-8886-5e044fb61251">

**Comment by wcornwell** [comment]
adding a known name makes this behavior go away, which is why the tests are passing
<img width="627" alt="Screenshot 2023-08-22 at 2 27 19 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/48dc7d0e-635d-4fbb-955e-89b1e8f9e5fc">

**Comment by ehwenk** [comment]
Try again
```
create_taxonomic_update_lookup(taxa = c("Eucalyptus", "Banksia asdasd"), resources = resources)
```

I'm pretty sure this was part of another problem Daniel and I fixed this afternoon

**Comment by wcornwell** [comment]
seems like it's fixed in the refactor.  add as a test to https://github.com/traitecoevo/APCalign/blob/refactor/tests/testthat/test-alignment_executes.R ?
