### ISSUE TITLE
Need to standardise `taxon_rank` values

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/APCalign#133]
@wcornwell  @fontikar 
Two issues:
- we currently have a mix of lowercase and uppercase `taxon_rank` values
- we currently have a mix of English and Latin `taxon_rank` values

We should select a standard and implement it when the taxonomic resources are read in.

It seems that lowercase is the standard (DarwinCore, International Association of Plant Taxonomy, a style guide), but NSL uses uppercase:
- https://stylemanual.com.au/contents/subject-areas/biology/naming-organisms/general-principles-formal-taxonomic-names
- http://rs.tdwg.org/dwc/terms/taxonRank
- https://www.iapt-taxon.org/nomen/pages/main/art_3.html
- https://www.iapt-taxon.org/nomen/pages/main/art_4.html 

Also, do we want the output values to be:

```form, variety, subspecies, species, genus, family, class subclass```

or

```forma, varietas, subspecies, species, genus, familia, classis subclassis```

Right now, the column headers are in English (e.g. genus, family, subclass), but the values in the taxon_rank column are Latin (Familia, Varietas, Forma)

**Comment by wcornwell** [comment]
english
