### ISSUE TITLE
Planning our documentation

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#141]
There are 4 main forms of documentation in the package: 

1. README (how to install, point to tutorial and other sources of help, where for bugs, how to contribute)
2. Helpfiles (function parameters, what it returns and the 'metadata' of what is returned using 'details' 'value' 
3. Vignette (Demo of core functions, for beginners and novice) 
4. Articles (Shows only on pkgdown website - In depth explainers of key concepts, for those seeking clarification and interest in concepts) 

We need to decide how to break out our main ideas into the various documentation. 

**Current Articles:** 
- Caching Taxonomic Resources #79 
- Aligning (Fuzzy match) #78 

What @ehwenk mentions here is a good place to start:
There are two main "processes", aligning and updating. In addition there is the pre-processing

- **pre-processing:** standardise_names and strip_names  ensure that the name strings are easier to align in the next step.
- **aligning:** match_taxa actually does the fuzzy matching, working out the taxon rank, taxonomic resource, if there is any name in APC/APNI that matches; align_taxa is the user interface where you specify the parameters for match taxa
- **updating:** update_taxa does the actual processing of taking the "aligned names" and updates them to accepted and/or suggested names;  `create_taxonomic_output_table` is the wrapper for that
I think there needs to be an article for each process.

@ehwenk : I also think in the documentation we should not call this overall process "standardising", since that isn't really what we're doing - and the function `standardise_names` exists as well which is completely separate

@ehwenk has a table that describe the behaviour of update_taxonomy for different use cases of taxonomic splits 
This table (and others) need to be converted and placed in the updating article

**Comment by fontikar** [comment]
@wcornwell found TNRS as inspiration to guide convo: https://tnrs.biendata.org/about/#howtnrs

**Comment by fontikar** [comment]
My feeling is 'preprocessing', doesn't need an entire article but a short paragraph in the 'aligning' article to mention that it occurs before alignment. The goal is to not 'write an in-depth manual' of everything APCalign does, only the main "processes" aligning and updating.

**Comment by wcornwell** [comment]
here is the TNRS paper: https://link.springer.com/article/10.1186/1471-2105-14-16.  The big challenge is going to be justifying an Australian specific tool, so we've got to have a clear argument about that (I think we can do it).

**Comment by ehwenk** [comment]
I agree pre-processing is just a brief paragraph! But just to indicate why we have those functions

**Comment by fontikar** [comment]
Use cases is also a good Article to have @rubysaltbush is going to help with! I think planning those use cases should go to #22

**Comment by wcornwell** [comment]
I vote for working on the paper first, and the website second...

**Comment by fontikar** [comment]
agreed! +1 getting the paper structure down first would better inform the documentation @wcornwell can you start an issue thread for ms structure

**Comment by fontikar** [comment]
@ehwenk for nicer formatting tables: https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r

**Comment by wcornwell** [comment]
we're beyond this now
