### ISSUE TITLE
ms structure

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#142]
## Implementation

- Taxonomic sources
- Pre-processing / Parsing
- Fuzzy matching
- Taxonomic updating
- Establishment means

## Comparison with existing tools

- TNRS
- others?

## Use cases

- Large dataset name updating
- Large dataset native/introduced
- Gap analysis (requires complete list)

**Comment by wcornwell** [comment]
<img width="1282" alt="Screenshot 2023-08-31 at 1 39 08 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/98d44218-6c2f-4fbc-a8e3-861aa04a6daa">

**Comment by wcornwell** [comment]
list of different behaviors from TNRS:
<img width="665" alt="Screenshot 2023-08-31 at 2 54 43 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/e3bff34e-fba7-4459-8f74-db057987122c">

**Comment by wcornwell** [comment]
<img width="663" alt="Screenshot 2023-08-31 at 2 56 02 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/d99c70f7-e73b-4dd2-b8de-6c95bf349e5a">

**Comment by wcornwell** [comment]
There is a general point to make that using geography (i.e. knowing you're in Australia or UK or Argentina or whatever) will improve the performance of name matching.

**Comment by wcornwell** [comment]
@fontikar just in a meeting with some proper software developers and they were very keen on making this distinction: ![Screenshot_20230907-084003.png](https://github.com/traitecoevo/APCalign/assets/5534161/edd832c7-0b02-4500-a4f4-2a5c7b05bef6) 

My current hypothesis for why is that if you have too much tech babble in the user story, things just getting muddled.

**Comment by fontikar** [comment]
> list of different behaviors from TNRS: <img alt="Screenshot 2023-08-31 at 2 54 43 pm" width="665" src="https://user-images.githubusercontent.com/5534161/264538247-e3bff34e-fba7-4459-8f74-db057987122c.png">

They are sooo different holy moly!

**Comment by fontikar** [comment]
> @fontikar just in a meeting with some proper software developers and they were very keen on making this distinction: ![Screenshot_20230907-084003.png](https://user-images.githubusercontent.com/5534161/266159276-edd832c7-0b02-4500-a4f4-2a5c7b05bef6.png)
> 
> My current hypothesis for why is that if you have too much tech babble (eg edge cases) in the user story, things just getting muddled.

This is so helpful! Thanks @wcornwell, I like the distinction. I would argue most documentation is for user stories and how to use software for each one. The technical details I think is really for the paper and book like documentation where the reader is expecting details

**Comment by wcornwell** [comment]
moving to https://github.com/traitecoevo/APCalign-MS
