### ISSUE TITLE
add row_number to incoming list of names in align_names

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/APCalign#146]
We have a row_number added to keep track of the sequence for update_taxonomy, but not for `align_taxa`. Incoming lists of names are immediately resorted alphabetically. This causes an immediate problem when I just ran the entire AusTraits original name list, because I couldn't match back info like dataset_id to the output. 

@dfalster What is the best way to implement this?

**Comment by dfalster** [comment]
I did fix all this at some point, and there are tests, so not sure how it's breaking now. Data get's resorted before being returned. See https://github.com/traitecoevo/APCalign/blob/master/R/align_taxa.R#L160

Can you post some example code highlighting the issue (with example dataset of a few rows)?

**Comment by dfalster** [comment]
At some point Lizzy you replaced the sorting in update_taxonomy with the approach using row_number. But the new approach doesn't ensure we have the same number of row.s

**Comment by ehwenk** [comment]
I've tested it again - and it is working. I must have done something strange yesterday. Closing the issue.
