### ISSUE TITLE
new repo?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#151]
We probably need a new repo for code that's associated with the MS, but not the package?

**Comment by fontikar** [comment]
I have no strong feelings for this, we can use tags and tag "manuscript issues" and "package issues"?

**Comment by wcornwell** [comment]
i was more thinking: where should i put the code in #152 ?

**Comment by fontikar** [comment]
Yes I think this is a good idea and there is some code I want too for comparing different tools. Shall I go ahead and make traitecoevo/APCalign-ms ?

**Comment by fontikar** [comment]
new repo for ms code: https://github.com/traitecoevo/APCalign-ms
