### ISSUE TITLE
Error caused by accepted list name?

### ISSUE THREAD

**Issue by yangsophieee** [traitecoevo/APCalign#154]
I'm getting this error when I try run `create_taxonomic_update_lookup` on GBIF taxa in Australia. 

![Pasted image 20231004202714](https://github.com/traitecoevo/APCalign/assets/78716301/b916d38f-9a4e-41d6-bbfc-7b3ef732d3f7)

It looks like there is a value in `accepted_list` where `accepted_list[i]` evaluates to "microcarpaea /", meaning [Line 44](https://github.com/traitecoevo/APCalign/blob/7f1eaf3c35f2f8f5f0b9ea6f94afc71ba8a54ab4/R/fuzzy_match.R#L44) evaluates to NA since it doesn't pick up the slash symbol. Later on, on [Line 103](https://github.com/traitecoevo/APCalign/blob/7f1eaf3c35f2f8f5f0b9ea6f94afc71ba8a54ab4/R/fuzzy_match.R#L103), it means that the second condition will evaluate to NA, so the overall `if` expression evaluates to NA. The taxon that it was trying to align at this point was "microcarpaea rbr". The non-stripped version is "Microcarpaea  R.Br.".

Any ideas, @wcornwell @fontikar?

**Comment by yangsophieee** [comment]
Could it be these taxa in resources$`APC (known names):
Microcarpaea/Peplidium sp. B
Microcarpaea/Peplidium sp. C
Microcarpaea/Peplidium sp. D
Microcarpaea/Peplidium sp. E

**Comment by yangsophieee** [comment]
I found the issue is Microcarpaea/Peplidium sp. D in `resources$`APC list (known names)` (the binomial column is "microcarpaea /").

**Comment by wcornwell** [comment]
hmmmm @ehwenk ?

**Comment by wcornwell** [comment]
@yangsophieee, what name is getting passed in that's causing the error?

**Comment by yangsophieee** [comment]
@wcornwell "Microcarpaea  R.Br." (but with two spaces for some reason)

**Comment by wcornwell** [comment]
<img width="1052" alt="Screenshot 2023-10-05 at 2 39 21 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/bf7aa211-a210-47ad-9f91-71a6abfc3b20">

**Comment by ehwenk** [comment]
I think the mistake was in match_17a, where fuzzy_match was using the `cleaned_name` rather than `stripped_name`, because the two `strip_name` functions should both remove the `\` and binomial/trinomial should be derived from `stripped_name2` not from a `cleaned_name`, so I'm confused how the binomial can have a `\` in it. @yangsophieee how did you generate the binomial?

```
> txt <- "Microcarpaea/Peplidium sp. D"
> standardise_names(txt)
[1] "Microcarpaea/Peplidium sp. D"
> standardise_names(txt) -> txt2
> strip_names(txt2)
[1] "microcarpaea peplidium sp d"
> strip_names_2(txt2)
[1] "microcarpaea peplidium d"
```

**Comment by yangsophieee** [comment]
The binomial "microcarpaea /" comes from Microcarpaea/Peplidium sp. D in `resources$APC list (known names)`. The `binomial` column says "microcarpaea /" for this taxon.

**Comment by ehwenk** [comment]
OK, another attempt - it is a weird symbol that isn't part of [:punct:] - @yangsophieee can you try now on the branch `bug-in-fuzzy-match`

**Comment by wcornwell** [comment]
working for me :)

**Comment by wcornwell** [comment]
<img width="1060" alt="Screenshot 2023-10-10 at 11 39 33 am" src="https://github.com/traitecoevo/APCalign/assets/5534161/3692afe7-868a-46fb-9ae3-67ea0286cef6">

**Comment by wcornwell** [comment]
seems fixed
