### ISSUE TITLE
rename `imprecise_fuzzy_matches` to `two_level_fuzzy`?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#155]
I think that's what it does???  Or if not, what does it do?  @fontikar and I were trying to figure out how to explain this for the MS...

**Comment by ehwenk** [comment]
@wcornwell I feel like `imprecise_fuzzy_matches` is a very accurate name. There are no sliders for this, so the fuzziness is fixed - and based on AusTraits, often inaccurate. I see it as a tool to explore possible names but shouldn't be used if you aren't planning on verifying every match, and therefore turn it off as a default.

**Comment by wcornwell** [comment]
poorly worded issue by me, sorry.  

The main issue for the user is that we've exposed:
```
  fuzzy_abs_dist = 3,
  fuzzy_rel_dist = 0.2,
  fuzzy_matches = TRUE,
  imprecise_fuzzy_matches = FALSE,
```
The first three are pretty clear, but for `imprecise_fuzzy_matches` and the documentation just says:

`Imprecise fuzzy matches are turned off as a default.`
 
which is highly cryptic for the user.  @fontikar and I were trying to figure out how to improve the documentation, but also we didn't really understand what to say there.  

Then we got confused about whether you could get the same effect by going to a high value of `fuzzy_abs_dist`.

but maybe we should just change the documentation for `imprecise_fuzzy_matches` to something like:

"a way to get a wider range of possible names, corresponding to very distant spelling mistakes. This is FALSE as default and should always be used with supervision" 

or something like that?
