### ISSUE TITLE
Genus sp. names in resources$`APC list (known names)`$canonical_name causing matching at the species level instead of genus level

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#157]
but for some reason if it's misspelled it does work, maybe because of the order of the operations in match_taxa:

<img width="1218" alt="Screenshot 2023-10-10 at 2 33 54 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/477895ad-b719-4ecf-8cc9-7869ac4bef3b">

**Comment by wcornwell** [comment]
the first one should be going to match_01a, but maybe it's getting inappropriately captured by match_06b because `resources$`APC list (known names)`$canonical_name` has `Dryandra sp.` in it

**Comment by wcornwell** [comment]
<img width="663" alt="Screenshot 2023-10-10 at 2 40 06 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/cbf461e4-3362-4738-997d-95d5eac28cbb">

**Comment by wcornwell** [comment]
there are a fair number of "Genus sp." in resources$`APC list (known names)`$canonical_name which leads them all to come back as "matching" at the species level, when they should be at the genus level.

<img width="1393" alt="Screenshot 2023-10-10 at 2 45 13 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/e8abc3ff-662a-490c-adbe-999e1da2e453">

**Comment by ehwenk** [comment]
Yes, I've fixed this - next pull request submitted. When matches 5 & 6 (perfect APC matches) were moved to the front of the match list, I didn't consider these could now "capture" genus-level matches by mistake. So matches 5 & 6 now only consider species/infraspecific taxon names (in APC)

**Comment by wcornwell** [comment]
fixed here: https://github.com/traitecoevo/APCalign/pull/158
