### ISSUE TITLE
Getting latest release version number

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#160]
Our current mechanism of retrieving the latest 'default' version is by typing out the version number. This gets a bit clunky as we have more and more releases. 

Plan is to write a function that will pull the version numbers from releases and default_version should return the latest one

**Comment by wcornwell** [comment]
```
  # Fetch the latest release information using the GitHub API
  url <-
    paste0(
      "https://api.github.com/repos/",
      "traitecoevo",
      "/",
      "APCalign",
      "/releases/latest"
    )
  response <- httr::GET(url)
  release_data <-
    jsonlite::fromJSON(httr::content(response, "text"))
```

**Comment by wcornwell** [comment]
code copied from infinitylists

**Comment by wcornwell** [comment]
https://github.com/traitecoevo/infinitylists/blob/006f937156c4edaf3d859203b291367d4edea909/R/global.R#L157
