### ISSUE TITLE
Internet resources should fail gracefully

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#163]
CRAN related task requested by maintainers. 

https://community.rstudio.com/t/internet-resources-should-fail-gracefully/49199/4 

Will also add CRAN badge once I've addressed this :)

**Comment by wcornwell** [comment]
i think this might be enough: https://github.com/traitecoevo/APCalign/commit/3b17bb57a5964815d97f1268dc308e75ac548886?  or do we need to do more?
