### ISSUE TITLE
Enhancement of `identifier` argument, to accept columns and not a string

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#177]
I am not sure how common this use-story is but I discovered a bug while building the APCalign app . I suspect this is common via app because entry to APCalignis more feasible and folks would probably want to upload any dataset and get some output.
I was using this testing dataset from Dryad: https://datadryad.org/stash/dataset/doi:10.5061/dryad.j9kd51cgr
`create_taxonomic_update_lookup(data$Species, identifier = data$Site)`  fails (specifically `match_taxa` on Lines 70)

The error:
```Checking alignments of 530 taxa

  -> 0 names already matched; 0 names checked but without a match; 530 taxa yet to be checked
Error in dplyr::mutate(., identifier_string = ifelse(is.na(identifier),  : 
  ℹ In argument: `identifier_string = ifelse(...)`.
Caused by error:
! `identifier_string` must be size 530 or 1, not 761.
I think this happened because we align_taxa to unique values of original_name  (There are 530 unique original_name ), but identifier is has a length of 761.
```
Here is a scaled down reprex:
```
data <- tibble::tibble(Species = c("Banksia sp", "Banksia sp", "Acacia sp"),
               Site = c("Site A", "Site B", "Site C"))

data 

head(data)

output <- create_taxonomic_update_lookup(data$Species, identifier = data$Site, resources = resources)

length(data$Species)
length(data$Site)

length(unique(data$Species))
length(unique(data$Site))
```
I recall our discussion that the output should return distinct() values for original_name but maybe we need to rethink this…? Or have an `if` statement when identifiers are present then the output should be `distinct(original_name , identifier)`

 Attached is the testing dataset [westerband_2022_wdate.csv](https://github.com/traitecoevo/APCalign/files/14089370/westerband_2022_wdate.csv)

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/06fe7088d545909eacbbf03aa96d87dc9359a2b1
