### ISSUE TITLE
Issues with arrow on cran

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#178]
We're using the package {arrow} to load parquet files. However arrow has violated some conditions of cran and will shortly be removed, after which APCalign will be affected. The arrow team are working to resolve this and have some suggested approach below. 

@fontikar or @wcornwell - could you handle this?

From CRAN: 

> Package 'arrow' violates the CRAN policy on downloading binary software and continued to do so in multiple re-submissions, each taking hours of CRAN time.  The CRAN team is not prepared to spend any more time on it, so it will be removed on Feb 9. That will make the packages requiring it (directly or indirectly),

From arrow team:

> We believe that you have received an email from CRAN informing you of arrow’s impending archival.  Please bear with us for the moment; we are aware of this and working to get this resolved before their deadline.  We’ll let you know as soon as we have an update. Best wishes, Nic Crane

Suggested interim response:

> We’re still working to respond to CRAN’s evolving requirements on external C++ libraries, and while we believe we know what we need to do to meet the new requirements, it’s not clear that we can resolve everything before February 9.
> As an interim measure, we are starting to submit PRs to packages that import arrow to make sure they have the updates they need to stay on CRAN while arrow is removed. It won’t be possible for us to get to all of the packages that rely on arrow, but if we haven’t gotten to yours, feel free to ping us here and we can make suggestions and offer code review.
> For packages that `Suggest` arrow, it should be sufficient to add `Additional_repositories: [https://p3m.dev/cran/2024-02-02`](https://p3m.dev/cran/2024-02-02%60) to your `DESCRIPTION` to indicate that arrow can be installed from the snapshot in the Posit Package Manager repo (package version 14.0.0.2). Alternatively, you can instead get the latest pre-release version of arrow by instead using `Additional_repositories: https://apache.r-universe.dev`/ or `Additional_repositories: [https://nightlies.apache.org/arrow/r`](https://nightlies.apache.org/arrow/r%60).

**Comment by wcornwell** [comment]
nothing we can do atm?  let's just wait and see.
