### ISSUE TITLE
Caching UI and documentation

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#194]
As I understand the code is designed to do this via the `output` option:

```
test <- create_taxonomic_update_lookup(c("Acacia suaveolens","Pinus coulterii",
                                       "Actinotus helianthii"),
                                     resources=resources, output = "cache.csv")
```

If `"cache.csv"` exists than it checks if there are new names to check and proceeds to check them, then overwrites the file with the superset.  

Was that actually the intention @ehwenk? Are we happy with that?

**Comment by fontikar** [comment]
I think so @wcornwell but currently this doesn't work see: 
https://github.com/traitecoevo/APCalign/pull/192#discussion_r1569899562

There was discussion a while back to make this working but it got deprioritised. https://github.com/traitecoevo/APCalign/issues/140

**Comment by wcornwell** [comment]
I have it mostly revived on my branch

**Comment by wcornwell** [comment]
95% of the code for it was still in there, and I think not so hard to get it working again--if we want that functionality.

If we don't want it anymore, I can remove.
