### ISSUE TITLE
updating families

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/APCalign#195]
Currently we update outdated genera to their current genus name (e.g. Dryandra sp. to Banksia sp.). However we do not include either the ability to detect outdated family names nor to update them. Within the AusTraits datasets there were instances of Epacridaceae sp., Compositae sp,, and Gramineae sp. 

We should both include a match algorithm to detect these names and a step within `update_taxonomy` to update these names.

**Comment by ehwenk** [comment]
Steps to implement this include:

1. Creating an additional dataframe within `resources` that includes `family synonyms`
2. Add a match algorithm toward the very end of `match_taxa.R` that detects these names
3. Adding additional loops within `update_taxonomy` to update these names

**Comment by wcornwell** [comment]
does APC provide a family level synonymy?  Also, some of them are splits (e.g. Scrophulariaceae and Liliaceae)....

**Comment by ehwenk** [comment]
Yes, APC does provide family-level synonymy. 

So far I've (1) created an additional dataframe in resources and (2) added in a match-algorithm to catch typos in family-level names. I started working through the synonyms part, but this requires a fair bit of extra code and (I think) a new column with family-level taxon_id's. I'm doing that now.

Dealing with family-level splits/merges would be a lot of new code for very limited use cases, so I don't recommend we do that.

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/3d409bc644515d32eb012e67347079a55767c0e9
