### ISSUE TITLE
Suggested changes to standardise names

### ISSUE THREAD

**Issue by ehwenk** [traitecoevo/APCalign#197]
Suggested changes to standardise names

-the pattern `[:alpha:]/[:alpha:]` should become `[:alpha:] / [:alpha:]`
- remove punct that is at the beginning of a name string.

In part this is accomplished by changing lines 28-35 in standardise_names.R to
```
 taxon_names %>%
    ## remove ? and * throughout
    f("\\?", "") %>%
    f("\\*", "") %>%
   f("\\(","") %>%

    ## hybrid markers and other non-standard characters used are replaced with 
    ## the standard equivalent (e.g. x, \)
    stringi::stri_trans_general("Any-Latin; Latin-ASCII") %>%
```

- hopefully this will also deal with the corner case for the APC-accepted name "(Dockrillia pugioniformis x Dockrillia striolata) x Dockrillia pugioniformis"
- changes to the fuzzy matching algorithm proposed will require that all input names begin with A-Z or they will be excluded. It is therefore important that pre-processing creates valid names

**Comment by dfalster** [comment]
Hi Lizzy, feel free to try implementing, branching off develop
