### ISSUE TITLE
updating website

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#199]
Somethings will have changed after this round of improvements.

**Comment by wcornwell** [comment]
This might be something else actually: <img width="784" alt="Screenshot 2024-04-29 at 5 11 47 PM" src="https://github.com/traitecoevo/APCalign/assets/5534161/c7553fc5-c8df-4b48-80df-8c5f03ec0821">

**Comment by wcornwell** [comment]
@fontikar ?

**Comment by fontikar** [comment]
I think we will need to merge develop into Master before we resubmit to CRAN. but can update the workflow yes
