### ISSUE TITLE
fix CRAN issue before release

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#205]
<img width="754" alt="Screenshot 2024-04-29 at 4 50 37 PM" src="https://github.com/traitecoevo/APCalign/assets/5534161/52851406-8d25-4290-8d0a-6225defc6d47">

**Comment by wcornwell** [comment]
this is probably a priority as we want to be on CRAN when the paper comes out?

**Comment by fontikar** [comment]
I'm on it now!

**Comment by fontikar** [comment]
@wcornwell where is test-connection failing??

**Comment by wcornwell** [comment]
'default_version' is checking GitHub releases and if GitHub is down for a second, then it errors out, I think.

**Comment by fontikar** [comment]
We didn't fix this and I was so confused!
