### ISSUE TITLE
Swap adist for stringdist

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#215]
As noted by @wcornwell in https://github.com/traitecoevo/APCalign/issues/180#issuecomment-2087805540, we can swap out `adist` for a faster alternative 

![](https://private-user-images.githubusercontent.com/5534161/327025452-49ad1a94-fef8-4320-9da6-f9a3c783ff78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MjY3NTgsIm5iZiI6MTcxNDUyNjQ1OCwicGF0aCI6Ii81NTM0MTYxLzMyNzAyNTQ1Mi00OWFkMWE5NC1mZWY4LTQzMjAtOWRhNi1mOWEzYzc4M2ZmNzgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDFUMDEyMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDA3ZDFiMjhlZDZkN2VmYTY5NGQ4OGRlN2NjMmU3ZjQ1YWExNWNjNGIwNjVjOTI4YTMxNDg5ODBhYjFmM2ZkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.x7p6mcNizv-9-d8hGEzoTClK6o6wpbxlW4UtK9BhpV8)

**Comment by wcornwell** [comment]
@ehwenk Interesting bit from the `stingdist` help files

> The metric you need to choose for an application strongly depends on both the nature of the string (what does the string represent?) and the cause of dissimilarities between the strings you are measuring. For example, if you are comparing human-typed names that may contain typo's, the Jaro-Winkler distance may be of use. If you are comparing names that were written down after hearing them, a phonetic distance may be a better choice.

**Comment by ehwenk** [comment]
@wcornwell @dfalster 

So much for my hour of coding - immediately the same output with stringdist, method = "dl". At least now I know my logic has an official name. 

I'll remove my "wordy" code and run all tests.

**Comment by ehwenk** [comment]
![image](https://github.com/traitecoevo/APCalign/assets/8701562/0ef39863-c4d5-461c-9e57-83522e3d838f)

**Comment by wcornwell** [comment]
interestingly, this probably makes #162 obsolete.  Looks like part of their C++ magic is low-level parallelization.

see: https://www.rdocumentation.org/packages/stringdist/versions/0.9.12/topics/stringdist-parallelization

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/a8c763231c46172c265cd66c7d22a614143e989a
