### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/APCalign#22]
I'll put some time into updating this package sometime soon. It would be helpful to better understand use cases. If anyone could document use cases for the package, that would be very helpful. Particularly if they're not met by current functionality.

Thoughts @wcornwell @rubysaltbush @eflower @ehwenk  

Thanks!

**Comment by wcornwell** [comment]
adding @tmesaglio and @yangsophieee

**Comment by wcornwell** [comment]
for me #20 is the key feature that would be useful, since taxonomic versioning is a mess, be organized about that here could be a key contribution.

**Comment by yangsophieee** [comment]
I haven't used this package before, but just to provide an example use case, I'd like to align a list of plant taxa of many different taxonomic ranks (family, genus, species, subspecies) with APC so I can search for them in AusTraits. Does the package handle 'Melaleuca', 'Melaleuca sp.' vs 'Melaleuca spp.'? I haven't tested how the functions work so apologies if my question isn't applicable!

**Comment by rubysaltbush** [comment]
Hey all - documenting another use case, I had data I wanted to submit to AusTraits but it was a mix of Australian and international species. Using `ausflora::align_taxa` with `fuzzy_matching = FALSE` I was able to filter the non-Australian taxa out of my dataset. Simplified code exemplifying this is below:

```
library(ausflora)
library(tidyverse)

# get pollination data
pollination <- readr::read_csv("data_input/pollination_macroevolution_datatopublish_20221125_FULL.csv")

# match names to Aus species only (fuzzy matching off)
poll_aligned <- ausflora::align_taxa(pollination$taxon_name, fuzzy_matching = FALSE)

# 226 names directly match accepted Aus taxa, 17 known names and 23 APNI names
# probably many exotics
# update taxonomy
poll_updated <- ausflora::update_taxonomy(poll_aligned$aligned_name)

# remove "unplaced" or "misapplied" taxa as these likely don't occur in Aus
poll_updated <- poll_updated %>%
  dplyr::filter(taxonomicStatusClean %in% c("accepted", "taxonomic synonym")) %>%
  # and condense down
  dplyr::select(aligned_name, taxonomicStatusClean, alternativeTaxonomicStatusClean, canonicalName)

poll_aligned <- poll_aligned %>%
  dplyr::select(original_name, aligned_name, source)

# join all back together and filter out unplaced or non-Australian taxa
poll_for_austraits <- pollination %>%
  dplyr::rename(original_name = taxon_name) %>%
  dplyr::left_join(poll_aligned, by = "original_name") %>%
  dplyr::left_join(poll_updated, by = "aligned_name") %>%
  dplyr::filter(!(is.na(canonicalName))) # filters out any taxa not matched to accepted APC taxa

# write data for Australian taxa to csv for submission to AusTraits
write_csv(poll_for_austraits, "data_output/pollination_for_AusTraits_2023.csv")
```

**Comment by ehwenk** [comment]
This is a great idea and definitely a parameter (& use case suggestion) we'll add to ausflora.

**Comment by wcornwell** [comment]
hi all, I re-wrote the front end of the package to try to capture 95% of use cases in one function `create_taxonomic_update_lookup`.  if any one has time to try it out, I'm curious if there is any common functionality that I missed.

**Comment by wcornwell** [comment]
now in the MS
