### ISSUE TITLE
CRAN release 1.1.0

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#237]
Prepare for release:

* [ ] `git pull`
* [ ] `urlchecker::url_check()`
* [ ] `devtools::build_readme()`
* [ ] `devtools::check()`
* [ ] `devtools::check_win_devel()`
* [ ] `git push`

Submit to CRAN:

* [ ] `usethis::use_version('patch')`
* [ ] `devtools::submit_cran()`
* [ ] Approve email

Wait for CRAN...

* [ ] Accepted :tada:
* [ ] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version(push = TRUE)`
* [ ]  `usethis::use_cran_baddge()`

**Comment by dfalster** [comment]
Thanks!

**Comment by dfalster** [comment]
I've uploaded it. Just waiting on conformation messages

**Comment by dfalster** [comment]
Gah, cran is offline for 16 days! Ok, will come back to it on Aug 16

![Screenshot 2024-08-04 at 7 36 22 AM](https://github.com/user-attachments/assets/1d34874c-103b-4ab4-b763-9e981cbf061d)

**Comment by dfalster** [comment]
Version 1.0.2 now on CRAN, now I'll push 1.1.0

**Comment by dfalster** [comment]
PS. My first ever push to cran, that I've completed myself. Thanks @fontikar @wcornwell for guidance!

**Comment by dfalster** [comment]
version 1.1.0 now on CRAN :)

**Comment by fontikar** [comment]
> PS. My first ever push to cran, that I've completed myself. Thanks @fontikar @wcornwell for guidance!

Amazing work Daniel! Congrats 🥇
