### ISSUE TITLE
Cleaning s lat from names before matching

### ISSUE THREAD

**Issue by rubysaltbush** [traitecoevo/APCalign#4]
A few points in my data set didn't match because they had "s lat" in the species names, rather than "sensu lato" or "s.l.". Could this be added to the regular expressions for cleaning_names before matching?

<img width="1178" alt="Screen Shot 2020-09-03 at 11 01 36 am" src="https://user-images.githubusercontent.com/68254917/92059556-e6d83480-edd4-11ea-9c93-70d2b267b899.png">

**Comment by dfalster** [comment]
Hi Ruby, Thanks! You can see [here](https://github.com/traitecoevo/apcnames/blob/b169266255397530821bbece9c63d36837eb3cc6/R/clean_names.R#L486) that we search on some terms but not others. Great if you can list here all the ones you find that should be included.

**Comment by ehwenk** [comment]
@rubysaltbush I'd missed this issue while fixing up `standardise_names` last week. What are all the abbreviations for `sensu stricto` and `sensu lato` that you've come across. I can add all variants to the function.

**Comment by rubysaltbush** [comment]
@ehwenk no dramas, I'll have a think but in this data set "s lat" was most common, have also seen "aff."  used between genus and species names (i.e. _Hibbertia_ aff. _fumana_, slightly different meaning but maybe related way of indicating some taxonomic uncertainty in the species ID). I haven't actually come across sensu stricto being used in species names as of yet

**Comment by ehwenk** [comment]
@rubysaltbush All the `aff`, `affinis` variants are being dealt this. They are all updated to `aff.` and then "shunted" to genus-level alignments, exactly because those are names that indicate a genus-level identification. They are reformatted as `genus sp. [original_name_string; dataset_id]`

**Comment by ehwenk** [comment]
closed with commit [a5e3775](https://github.com/traitecoevo/APCalign/commit/a5e37757c58654882f1e664f95e089e065842f47)
