### ISSUE TITLE
attempt to retrieve a subspecies using 'ssp.' annotation only retrieves the species

### ISSUE THREAD

**Issue by tmesaglio** [traitecoevo/APCalign#44]
If you run this code:

create_taxonomic_update_lookup(
  c(
    "Banksia integrifolia integrifolia"
  ),
  resources = resources
)

it retrieves Banksia integrifolia integrifolia as expected. Similarly, asking for Banksia integrifolia subsp. integrifolia also works

But if I ask for Banksia integrifolia ssp. integrifolia, it only retrieves the species name, not the subspecies

So 'ssp.' needs to be entered as an accepted notation for subspecies

Would have to check for other infraspecific ranks too, eg

v. or var.
form. or forma. or f.

**Comment by fontikar** [comment]
I'm happy to take this one! 
Tests for spp. and v. var. and form. or forma. or f.

@tmesaglio do you have some nice plant name examples that include var. and forma. you can share with me :)

**Comment by tmesaglio** [comment]
@fontikar Notelaea longifolia has f. longifolia, f. intermedia and f. glabra
Psydrax odorata has six different forms

some ones with var, include Ranunculus pentandrus,  Ranunculus pumilio and  Ranunculus sessiliflorus

let me know if you needed more

**Comment by fontikar** [comment]
You amaze me @tmesaglio 🥇 @ehwenk would these be a headache to add to `match_taxa`?  if so we can save it for next sprint!

**Comment by ehwenk** [comment]
I fixed the `ssp` problem earlier today as part of my strip_names bug fixes. `f` as a standalone letter should also be captured. And I'm just add a change to also capture `v`

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/d0de483dce5d00684a7f4ef25f0f87005a814c69
