### ISSUE TITLE
what should update_taxonomy("Acacia sp.",resources=resources) return?

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#50]

**Comment by fontikar** [comment]
Good question, one I am pondering about too! 

Few things that crossed my mind when using `update_taxonomy`

- It returns a table that is arranged alphabetically, this already throws me because my input is my taxonomic names is not in any alphabetically order. 
    - My suggestion is alphabetically sorting should be an option
- From my understanding, `update_taxonomy()` adds all a lot of taxonomy info to the `aligned_name` but it doesn't actually "replacing any synonyms to their current accepted name" as far I as I can tell! 

```
library(ausflora) 

resources <- load_taxonomic_resources(stable_or_current_data = "stable")

bad_austraits_names <- tibble(original_name = c("Actinostrobus acuminatus", 
                                "Actinostrobus arenarius",
                                "Aloe saponaria"))

aligned_austrait <- align_taxa(bad_austraits_names$original_name, resources = resources)

updated_austraits <- aligned_austrait$aligned_name |> update_taxonomy(resources = resources)

austraits_lookup <- create_taxonomic_update_lookup(bad_austraits_names$original_name, resources = resources)

bad_austraits_names |> left_join(austraits_lookup)
```

I reckon we change the name of the function? `add_taxonomy_info()` maybe?? 
I also think maybe include original_name as column will help user to see the connection to the output of `aligned_taxa()`

**Comment by wcornwell** [comment]
current high-level workflow:

```
user_data <-
  tibble(
    my_species_names = c(
      "Eucalyptus regnans",
      "Acacia melanoxylon",
      "Banksia integrifolia",
      "Commersonia rosea",
      "Not a species"),other_trait_data = rnorm(5))
resources <- load_taxonomic_resources()
taxon_lookup <-
  create_taxonomic_update_lookup(user_data$my_species_names, resources = resources)
output_data_with_updated_tax <- left_join(user_data, 
                                          taxon_lookup, 
                                          by = c("my_species_names" = "original_name"))
```

**Comment by wcornwell** [comment]
but currently all sp. names are getting dropped in `update_taxonomy` so it looks like: 
<img width="926" alt="Screenshot 2023-07-21 at 4 11 41 pm" src="https://github.com/traitecoevo/ausflora/assets/5534161/e30714fa-5b56-4327-bb84-276f9d3d9d49">

**Comment by wcornwell** [comment]
> "replacing any synonyms to their current accepted name" as far I as I can tell!

It does sometimes.  For above, **Commersonia rosea** becomes `apc_name` **Androcalva rosea** in `update_taxonomy`.

**Comment by fontikar** [comment]
> but currently all sp. names are getting dropped in `update_taxonomy` so `Acacia sp.` looks like: <img alt="Screenshot 2023-07-21 at 4 11 41 pm" width="926" src="https://user-images.githubusercontent.com/5534161/255088032-e30714fa-5b56-4327-bb84-276f9d3d9d49.png">

Is that the intended behaviour for Acacia sp. to go to NA? 

> > "replacing any synonyms to their current accepted name" as far I as I can tell!
> 
> It does sometimes. For above, _Commersonia rosea_ becomes `apc_name` _Androcalva rosea_ in `update_taxonomy`.

I think its important to distinguish that the name _Commersonia rosea_ becomes `apc_name` _Androcalva rosea_  in `create_taxonomic_update_lookup()` and `align_taxa()` **NOT** `update_taxonomy` 

![Uploading Screen Shot 2023-07-21 at 4.39.43 pm.png…]()

<img width="1021" alt="Screen Shot 2023-07-21 at 4 40 46 pm" src="https://github.com/traitecoevo/ausflora/assets/12161802/7df15dfd-82fa-479f-bd2f-3ec356db5511">

is `create_taxonomic_update_lookup` really a complete wrapper for `align_taxa` and `update_taxonomy`, it seems the output for `update_taxonomy` doesn't really get used directly in `create_taxonomic_update_lookup`

**Comment by wcornwell** [comment]
I think (but not 100% sure, could be wrong) that the Androcalva name first comes in in `update_taxonomy` but then the column naming gets changed in `create_taxonomic_update_lookup` ?
`<img width="1327" alt="Screenshot 2023-07-23 at 4 18 45 pm" src="https://github.com/traitecoevo/ausflora/assets/5534161/be845aa0-0a94-4213-9a16-b7ac0eab4a03">

**Comment by fontikar** [comment]
What happens when a user `update_taxonomy`?  e.g. [see ](https://github.com/traitecoevo/ausflora/blob/fc996574ca99ac65905040dccfa4cd3a806a682e/vignettes/ausflora.Rmd#L200)

Do users join back if they want? This adds more rows though since there are multiple rows of the same aligned_name in updated_gbif_taxa

```
aligned_gbif_taxa <- gbif_lite |> 
  drop_na(species) |>  
  pull(species) |> 
  align_taxa(resources = resources)


updated_gbif_taxa <- aligned_gbif_taxa |> 
  pull(aligned_name) |> 
  update_taxonomy(resources = resources)


# Join back to aligned_gbif_taxa manually
aligned_gbif_taxa |> 
  left_join(updated_gbif_taxa, by = join_by(aligned_name)) |> 
  filter(aligned_name == "Acacia aneura") 
  ```

**Comment by wcornwell** [comment]
replaced by #82
