### ISSUE TITLE
Reorganising R/

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#64]
Currently, unclear which files refer to which functions.
Best practice is to name of .R as the main function e.g. align_taxa.R 
Sub functions i.e. from switch() or helper functions are best stored under the main .R 

Will work on new branch `clean-r`

**Comment by wcornwell** [comment]
go for it!

**Comment by dfalster** [comment]
My only warning is not to do this scale of reorganisation while you have many other branches going. Reconciling them will be torturous.

**Comment by wcornwell** [comment]
got point, merge my branch before you start

**Comment by fontikar** [comment]
I think `strip_names()` and `strip_names2()`are worthy candidates to store in a `utils.R` since they are called by 2 different functions. 

Just documenting this decision here

<img width="556" alt="Screen Shot 2023-07-28 at 4 38 31 pm" src="https://github.com/traitecoevo/ausflora/assets/12161802/e6f7530b-7750-4657-ac44-831ba6cf713e">

**Comment by fontikar** [comment]
is `get_apc_genus_family_lookup()` getting used/will get used for something? Currently not called by any function. If not, I will remove?

**Comment by wcornwell** [comment]
that was requested by herve. low priority, but may develop this more later.  

i would just leave as internal for now.

**Comment by fontikar** [comment]
For `align_taxa()` are the arguments (`max_distance_abs = 3`, `max_distance_rel = 0.2`) being called?? I suspect arguments aren't being passed appropiately.

Looks like `align_taxa()` calls `match_taxa()` which calls `fuzzy_match(max_distance_abs, max_distance_rel)` - many many many times. 

Should I try pass `max_distance_abs` and `max_distance_rel` across all calls?

**Comment by fontikar** [comment]
Good idea, looks like a big scary task!

**Comment by fontikar** [comment]
Also this is REALLY cool

```
devtools::install_github("datastorm-open/DependenciesGraphs")
library(DependenciesGraphs)
library(devtools)
load_all()
dep <- envirDependencies("package:ausflora")
plot(dep)
```

<img width="844" alt="Screen Shot 2023-07-31 at 12 07 51 pm" src="https://github.com/traitecoevo/ausflora/assets/12161802/dcb6bff8-4ad3-41c0-9b39-fa803390ccfe">

**Comment by dfalster** [comment]
Addressed via https://github.com/traitecoevo/APCalign/commit/558ea560fa2bba1caa9bfc0308751ef71dfdca05 (#74)
