### ISSUE TITLE
Explainer on origin status

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#68]
Can we provide some kinda explanation for these different terms? @wcornwell said these are calculated from raw data. Maybe worth sticking in an article.Rmd for the pkgdown website. 

We need the methods on how these are calculated pls 😄 

```
library(purrr)
library(janitor)

 status_matrix |> 
+   select(-species) |> 
+   flatten_chr() |> 
+   tabyl()
 flatten_chr(select(status_matrix, -species))      n      percent
                       doubtfully naturalised   1120 2.371003e-03
                         formerly naturalised    277 5.863998e-04
                                       native  40336 8.538997e-02
            native and doubtfully naturalised      9 1.905270e-05
                       native and naturalised    136 2.879075e-04
                  native and uncertain origin      2 4.233933e-06
                                  naturalised   8765 1.855521e-02
                                  not present 421606 8.925258e-01
                             presumed extinct    101 2.138136e-04
                             uncertain origin     22 4.657327e-05
```

**Comment by wcornwell** [comment]
My guess is that these categories come from scaling up of [ACT plant counting efforts](https://www.anbg.gov.au/cpbr/ACT-census-2012/) and a [more recent one](https://www.anbg.gov.au/cpbr/ACT-census/index.html).  Herve will have the full documentation, but I'm guessing it's similar to the last link.

**Comment by dfalster** [comment]
We will involve some of the APC folk in the package and paper, so we can ask them to provide definitions

**Comment by wcornwell** [comment]
there is a whole paper on this now here: https://www.nature.com/articles/s41597-023-02746-3
