### ISSUE TITLE
Discussion on roles on ausflora

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#70]
I'd like to update the DESCRIPTION file at some point (not urgent!)

Leaving [this here ](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf) for reference

I would assume @ehwenk did all the heavy lifting for this package! 💪 
Would Anna Monroe and Anne Fuchs like to be named on package as key players in data distribution 📊 
Same with Carl with contentID 🗄️ 
and everyone wonderful found [here](https://github.com/traitecoevo/ausflora/graphs/contributors)

**Comment by wcornwell** [comment]
closing for now
