### ISSUE TITLE
Passing arguments `max_distance_abs` and `max_distance_rel` across all function calls

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#73]
For `align_taxa()` are the arguments (`max_distance_abs = 3`, `max_distance_rel = 0.2`) being called?? I suspect arguments aren't being passed appropiately.

Looks like `align_taxa()` calls `match_taxa()` which calls `fuzzy_match(max_distance_abs, max_distance_rel)` - many many many times. 

Should I try pass `max_distance_abs` and `max_distance_rel` across all calls?

_Originally posted by @fontikar in https://github.com/traitecoevo/ausflora/issues/64#issuecomment-1657358277_

**Comment by dfalster** [comment]
yes, I think because the names changed between different versions of the code.

But I'm not sure we'd want people to mess with these as much as I did in original version

**Comment by fontikar** [comment]
We expect most entry users to use `create_taxonomic_update_lookup()` so I would probably not include `max_distance_abs` and `max_distance_rel` there

For more "experienced" users and more sophisticated use cases, I think its reasonable to include across all calls, but maybe we should code in reasonable limits to distance arguments and use aborts for really outrageous choices?

**Comment by dfalster** [comment]
Good suggestions, that sounds good

For `create_taxonomic_update_lookup` could either not include the arguments, or only via `...`

**Comment by wcornwell** [comment]
i'm not fixing this, just cleaning up documentation to reflect current functionality for #67

**Comment by wcornwell** [comment]
closing in favor of #78

**Comment by fontikar** [comment]
As we discussed with @ehwenk, sliders available only in `align_taxa`

**Comment by ehwenk** [comment]
See commit 43b5fc75029fb57f76d4c652adc4bf88d4dccb11

**Comment by ehwenk** [comment]
closed by https://github.com/traitecoevo/APCalign/commit/e046cd2c2b170b3e275e98e2bd44ed020517da9e
