### ISSUE TITLE
Fuzzy match documentation 

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#78]
In R scripts and in articles

**Comment by fontikar** [comment]
Need to discuss whether flexibility to `max_distance_abs` and `max_distance_rel` is something we want to give to users and if so within what sensible ranges?

**Comment by fontikar** [comment]
There are 2 relevant .R files, fuzzy_match.R and match_taxa.R  (the former is called by the latter). match_taxa.R needs roxygen documentation and general commenting throughout the function about what is happening at each section, would be REALLY useful!!

**Comment by ehwenk** [comment]
Main documentation of functions is complete, but leaving this issue open as I still need to write up the match process for vignettes
