### ISSUE TITLE
Revised hex 

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#81]
A sticker that shows the core functionality (columns aligning)

**Comment by fontikar** [comment]
@dfalster imagery suggestion of plants lining up :D

**Comment by fontikar** [comment]
![APCalign_hex2](https://github.com/traitecoevo/APCalign/assets/12161802/dd4d151c-662e-441d-aaf5-803775096560)

What do we think folks?

**Comment by dfalster** [comment]
Hi Fonti! Cool idea. I like the colour, the addition of the aligned stack, and use of a flower. I have two comments. 

1. Feels a bit too heavily towards the left. How would it look with stalk coming out of the l instead of the APC?

2. Is there a risk the flower details are too fine for sticker size? 

3. Is it a Kangaroo paw? If so, is the leaf correct? From memory, K paws have quite a different leaf.

**Comment by fontikar** [comment]
![Untitled_Artwork 10](https://github.com/traitecoevo/APCalign/assets/12161802/5e785927-e831-4c09-b74e-febd264f4e0c)
![Untitled_Artwork 11](https://github.com/traitecoevo/APCalign/assets/12161802/1e72d5c4-5b39-48b1-abde-9ffdfe34f295)
![Untitled_Artwork 12](https://github.com/traitecoevo/APCalign/assets/12161802/ffa5e771-d302-48cc-b457-eb1be371c196)


A few more doodles, banksia stigmas(?) simplified!

**Comment by fontikar** [comment]
![Untitled_Artwork 13](https://github.com/traitecoevo/APCalign/assets/12161802/381ce681-e802-4cb8-b380-fd63bef5194e)

a random idea! the pink might be a bit much...

**Comment by dfalster** [comment]
I like the beige one best, or last pink, with coloured l but without the spikes

**Comment by fontikar** [comment]
<img width="573" alt="Screenshot 2023-11-13 at 10 12 28 am" src="https://github.com/traitecoevo/APCalign/assets/12161802/bb163fdd-d6b4-4a20-9d5c-5d9514272d52">

After some chats with @ehwenk, incorporating her suggestion of using the banskia and using the "partial styles (+ other fused parts)", we threw this one design together. Thoughts? Happy to adjust and incorporate feedback!

**Comment by dfalster** [comment]
I like it!

**Comment by fontikar** [comment]
Hooray! Will run with this for now and make vectors of each component for future us! Will create hex and share at next catch up
