### ISSUE TITLE
align_taxa has some weird behavior with genus level IDs (sp.)

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#88]
for some reason more than one species turns the aligned_name to NA:
<img width="716" alt="Screenshot 2023-08-03 at 3 40 18 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/bda76ae5-4ba1-4bb7-be4e-67111925c403">

**Comment by wcornwell** [comment]
also not sure what's up with the `[XXXX]`

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/8aabbc865da6efc86f9db67394b40f0fb72c32e5
