### ISSUE TITLE
Rename column names (apc_name and taxonomic_status_of_aligned_name)

### ISSUE THREAD

**Issue by fontikar** [traitecoevo/APCalign#93]
accepted_name (no authorship), and also display scientific_name (with authorship) in the output table of create_taxonomic_update_lookup

**Comment by fontikar** [comment]
Might be a good time to also rename `taxonomic_status_of_aligned_name` to `update_reason`

**Comment by ehwenk** [comment]
I think we have to retain the term `taxonomic_status` (in some capacity) - that is an official taxonomic term (https://dwc.tdwg.org/terms/#dwc:taxonomicStatus)

**Comment by wcornwell** [comment]
what about `full = TRUE` retains the APC terminology exactly and `full=FALSE` uses 
```
   original_name,
        aligned_name,
        updated_name = canonical_name,
        aligned_reason,
        updated_reason = taxonomicStatusClean
```
???

**Comment by wcornwell** [comment]
APC column names in this context are:
<img width="914" alt="Screenshot 2023-08-08 at 4 10 14 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/65cb221b-be72-4167-8371-7a95a6031065">

**Comment by wcornwell** [comment]
should i add `scientificNameAuthorship` to `full = FALSE`
