### ISSUE TITLE
) or ( surrounded by spaces causes an error in align_taxa

### ISSUE THREAD

**Issue by wcornwell** [traitecoevo/APCalign#97]
<img width="803" alt="Screenshot 2023-08-09 at 3 41 14 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/59c5b4e0-7203-4f23-99bb-c349841888a3">

**Comment by wcornwell** [comment]
without the spaces it behaves as expected:
<img width="792" alt="Screenshot 2023-08-09 at 3 44 52 pm" src="https://github.com/traitecoevo/APCalign/assets/5534161/bc7caebc-1d17-416e-8b0e-054f437ee720">

**Comment by wcornwell** [comment]
also in the same dataset: `"Dillwynia sp. ( Gibralter Range )"` and `"Daviesia sp. ( Wadbilliga NP - Deua NP )"`

**Comment by ehwenk** [comment]
closed with https://github.com/traitecoevo/APCalign/commit/d0de483dce5d00684a7f4ef25f0f87005a814c69
